services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_APPWRITE_ENDPOINT=${NEXT_PUBLIC_APPWRITE_ENDPOINT}
        - NEXT_PUBLIC_APPWRITE_PROJECT=${NEXT_PUBLIC_APPWRITE_PROJECT}
        - NEXT_PUBLIC_APPWRITE_PROJECT_NAME=${NEXT_PUBLIC_APPWRITE_PROJECT_NAME}
        - NEXT_PUBLIC_APPWRITE_DATABASE=${NEXT_PUBLIC_APPWRITE_DATABASE}
        - NEXT_PUBLIC_APPWRITE_USERS_COLLECTION=${NEXT_PUBLIC_APPWRITE_USERS_COLLECTION}
        - NEXT_PUBLIC_APPWRITE_FILES_COLLECTION=${NEXT_PUBLIC_APPWRITE_FILES_COLLECTION}
        - NEXT_PUBLIC_APPWRITE_BUCKET=${NEXT_PUBLIC_APPWRITE_BUCKET}
    ports:
      - "3000:3000"
    environment:
      - NEXT_APPWRITE_KEY=${NEXT_APPWRITE_KEY}
    env_file:
      - .env.local
